### ISSUE TITLE
Add Fosterer Role

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#599]
~~This is pending some discussion on the state of the policy model tests in Slack.~~
Per Slack and meeting discussion, we are going to leave policy unit tests as is for readability and ease of use. We will add fosterer role checks to all authz unit tests as indicated in acceptance criteria.

## Description
We are implementing users as fosterers and have created shared `AdopterFosterAccount` and `AdopterFosterProfile`. However, we need the `fosterer` role to actually assign the permissions for `fosterers` separately from `adopters`.

## Acceptance Criteria
- [x] User can be assigned a `Fosterer` role using rolify
- [x] `FOSTERER_PERMISSIONS` created and linked to fosterer role.
- [x] Fosterer role added to authorization tests

**Comment by mononoken** [comment]
For documentation, here is the main Slack message pending this issue. If anyone happens to have thoughts on this here, please share them!

---
I am making an issue and starting to work on the fosterer role that we discussed in yesterday’s meeting. This got me thinking about how the authz models are currently tested:
Right now, for the most part, all policy models are tested something like this:
```ruby
class PolicyTest
  context "#action?" do
    context "no user"
    context "adopter"
    context "staff"
    context "admin"
  end
end
```
I like this method as it documents clearly what each role can do given the policy. While it creates a lot of duplication in tests, I personally don’t think duplication in tests is a problem.

While I was working on the authz branch, I thought of a different approach that I am reconsidering now.

Currently, each role is  just a way to fetch a list of preassigned permissions per role:
```ruby
  ADOPTER_PERMISSIONS = %i[
    create_adopter_applications
    view_adopter_applications
    withdraw_adopter_applications
    create_adopter_foster_profiles
    manage_adopter_foster_profiles
  ].freeze
```
Because of this, another approach would be to test like this:
```ruby
class PolicyTest
  context "#action?" do
    context "user has x permission" do
      before do
        stub permission to user
      end
    end
  end
end
```
This would make some policy tests way slimmer as we are directly testing the permission behavior. The policy tests no longer have any idea that roles even exist, just like the policy objects themselves. We could also then test the roles separately to assert each role has the expected permissions.

What I like about this second approach is the tests reflect the actual code more. It makes the tests slimmer which can make it easier to refactor if necessary. Most importantly though, this approach also means that the policy tests are not coupled with roles at all. If we add a new role, the policy model tests do not have to be updated. They only need updating if something happens with the permissions . While I like this benefit, it’s not one we probably will feel often though because I doubt we will be adding many more roles. However, as time goes, the number of policies is definitely going to grow too as more features are added. This means that every time something does happen with roles, it’s going to require lots of upkeep in the policy model tests.

What do y’all think about this? I think it would be good to consider this approach before I add a “fosterer” context to every single policy model test.
