### ISSUE TITLE
Invite fosterers

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#636]
## Description
Fosterers are invited directly by staff. They do not sign up like adopters, who fill out forms for their account.

It is possible for a user to be both an adopter and a fosterer. This issue is only concerned with the case where a user does not yet exist and is being invited as a new user. A different flow will be used for existing users becoming fosterers.

A fosterer exists as a `User` with the `fosterer` role. They should also have an `AdopterFosterAccount`.

This will follow a similar flow to how users are currently invited to become a new staff user. See `./alta/users/invitation/new` path that is accessed from the staff dashboard link `Staff` on the sidebar. The role selection will not be required for this new form, as it will be auto-assigned as `fosterer`.

## Acceptance Criteria
- [ ] Create `Organizations::FosterInvitationsController` (use `Organizations::InvitationsController` as a guide)
- [ ] Views:
  - [x] Add dashboard sidebar link for `Fosterers` (add it above "Staff")
  - [x] Above link will redirect to a fosterers index (Note: these views for fosterers should mostly mimic the `Staff` link also found on dashboard sidebar)
  - [ ] Index should have a link to a form for inviting a new fosterer
- [ ] Create `Organizations::FosterInvititationPolicy` to authorize controller actions
  - [ ] Add `invite_fosterer` permission to `STAFF_PERMISSIONS` and any others as necessary to `authorizable.rb`
- [ ] Staff can fill a form to send invitation to fosterer by email
  - [ ] Form should not include role select. The role should be assigned in the controller.
- [ ] Fosterer receives an email inviting them to create a fosterer account
- [ ] Invited user should have:
  - [ ] User record with form attributes
  - [ ] Assigned the `fosterer` role using `rolify`
  - [ ] Associated `AdopterFosterAccount` is built for the User
- [ ] Tests
  - [ ] Unit test new policy class
  - [ ] Controller test for implementation of authorization in controller

## Additional Info
![fosterers-index](https://github.com/rubyforgood/pet-rescue/assets/81536479/a393bacb-2258-4c10-bd12-678f097c163e)
![fosterer-invite](https://github.com/rubyforgood/pet-rescue/assets/81536479/52822df6-a56a-45d2-90c3-c1762764eddc)

There are many components to this issue, but they should mostly be copies of existing actions. If there are any inconsistencies or confusion in this issue, please bring them to our attention here or on Slack!

**Comment by kasugaijin** [comment]
Hey @mononoken to answer the Questions:
- I don't think the AdopterFosterAccount will need any additional changes to it. The main adopter and fosterer flows will be dictated by presence of the `adopter` and `fosterer` roles on the User. 
- Let's keep the flow simple for MVP - the foster invitation is sent to a user email, same as we do for staff.

I think this unblocks this feature for building? Would be great to open it up while Githubbers are extra active on this project :)
