### ISSUE TITLE
Fosterers cannot apply for pets

### ISSUE THREAD

**Issue by mononoken** [rubyforgood/pet-rescue#656]
## Description
Only adopters should be able to see the "Apply to Adopt" button but currently it can be seen by someone who is a fosterer. 

This is happening because of the conditional logic in the view. The conditional logic needs to be refactored to use Action Policy to check that a user has permission to perform the `AdoptionApplication#create` action instead of directly checking for attributes like `adopter_foster_account` presence. See the Action Policy docs: https://actionpolicy.evilmartians.io/#/quick_start?id=basic-usage , specifically for the `allowed_to?` method.

I think this is only going to require updating of an if statement but please confirm. If it is going to take more work, let us know before delving too deep.

## Acceptance Criteria
- [ ] Fosterer does not see "Apply to Adopt" button
- [ ] Staff and adopter behavior continues to work as it does in main:
  - [ ] Staff does not see "Apply to Adopt" button
  - [ ] Adopter sees "Apply to Adopt" button

![adopt-apply](https://github.com/rubyforgood/pet-rescue/assets/81536479/5e5516c0-e29c-4432-8584-9dc9ca8d508f)

**Comment by Harry-kp** [comment]
Could you suggest how I can test the scenario where a fosterer does not see the "Apply to Adopt" button? Additionally, the `create` policy in `AdopterApplicationPolicy` returns ```false``` for:

- If the user has already applied for adoption
- If the user's profile is incomplete

Therefore, simply using the policy doesn't resolve the issue. We need to recheck these cases if the policy returns false because we need to show a different UI in these cases.

**Comment by mononoken** [comment]
> Could you suggest how I can test the scenario where a fosterer does not see the "Apply to Adopt" button? Additionally, the `create` policy in `AdopterApplicationPolicy` returns `false` for:
> 
> * If the user has already applied for adoption
> * If the user's profile is incomplete
> 
> Therefore, simply using the policy doesn't resolve the issue. We need to recheck these cases if the policy returns false because we need to show a different UI in these cases.

Thanks for asking @Harry-kp !

You are correct about the additional cases making relying on the existing policy tricky. However, I personally think this trickiness is hinting that the HTML code could benefit from some rearrangement.

I am envisioning moving the code around so that the `AdopterApplication.adoption_exists?` check is moved outside of the deeper if statement like this: 
```erb
<% if allowed_to?(:create?, with: AdopterApplicationPolicy, <more policy context info> %>
  <% if current_user.adopter_foster_account.adopter_foster_profile %>
    Current form for apply to adopt
  <% elsif current_user.adopter_foster_account %>
    Current prompt for completing profile
  <% end %>
<% elsif AdopterApplication.adoption_exists? ... %>
  Existing adopter application status info in this block
<% end %>
```
I like this layout since it separates the adoption_exists? logic from the rest of the actionable logic. And as a plus, I think it should get us the behavior this issue wants. What are your thoughts?

## testing
I am thinking it isn't necessary to system/feature test this button display. If the used policy already tests for the adopter and fosterer contexts, and we use the policy for the conditional logic, I think that may be sufficient. What are your thoughts on this @nsiwnf @kasugaijin ?

**Comment by kasugaijin** [comment]
Yes I agree re testing. I am becomine less of a fan of writing tests tightly coupled with the DOM because it makes the test suite very brittle.

**Comment by Harry-kp** [comment]
> > Could you suggest how I can test the scenario where a fosterer does not see the "Apply to Adopt" button? Additionally, the `create` policy in `AdopterApplicationPolicy` returns `false` for:
> > 
> > * If the user has already applied for adoption
> > * If the user's profile is incomplete
> > 
> > Therefore, simply using the policy doesn't resolve the issue. We need to recheck these cases if the policy returns false because we need to show a different UI in these cases.
> 
> Thanks for asking @Harry-kp !
> 
> You are correct about the additional cases making relying on the existing policy tricky. However, I personally think this trickiness is hinting that the HTML code could benefit from some rearrangement.
> 
> I am envisioning moving the code around so that the `AdopterApplication.adoption_exists?` check is moved outside of the deeper if statement like this:
> 
> ```
> <% if allowed_to?(:create?, with: AdopterApplicationPolicy, <more policy context info> %>
>   <% if current_user.adopter_foster_account.adopter_foster_profile %>
>     Current form for apply to adopt
>   <% elsif current_user.adopter_foster_account %>
>     Current prompt for completing profile
>   <% end %>
> <% elsif AdopterApplication.adoption_exists? ... %>
>   Existing adopter application status info in this block
> <% end %>
> ```
> 
> I like this layout since it separates the adoption_exists? logic from the rest of the actionable logic. And as a plus, I think it should get us the behavior this issue wants. What are your thoughts?
> 
> ## testing
> I am thinking it isn't necessary to system/feature test this button display. If the used policy already tests for the adopter and fosterer contexts, and we use the policy for the conditional logic, I think that may be sufficient. What are your thoughts on this @nsiwnf @kasugaijin ?

The proposed new structure seems good to me. The only catch here is 
-  To cater for the above solution, we have to lose some constraints in the policy. Like we have to allow create permission even if the profile is incomplete. This will affect the controller logic and the same redundant check will have to be applied there. I am thinking of this way.

```
<% if allowed_to?(:create?, with: AdopterApplicationPolicy, <more policy context info> %>
    Current form for apply to adopt
<% else> 
    <% if AdopterApplication.adoption_exists?... %>
       Existing adopter application status info in this block
    <% elsif current_user.adopter_foster_account.present? && current_user.adopter_foster_account.adopter_foster_profile.empty? %>
       Current prompt for completing profile
    <%end%>
<% end %>
```
This will separate your logic of whether to show the adoption form or not. If the answer is no, the else block will include the logic of the alternative component which we will be rendering based on some checks.

Also, this will not alter the logic of existing policy. Thoughts? @mononoken

**Comment by mononoken** [comment]
> > > Could you suggest how I can test the scenario where a fosterer does not see the "Apply to Adopt" button? Additionally, the `create` policy in `AdopterApplicationPolicy` returns `false` for:
> > > 
> > > * If the user has already applied for adoption
> > > * If the user's profile is incomplete
> > > 
> > > Therefore, simply using the policy doesn't resolve the issue. We need to recheck these cases if the policy returns false because we need to show a different UI in these cases.
> > 
> > 
> > Thanks for asking @Harry-kp !
> > You are correct about the additional cases making relying on the existing policy tricky. However, I personally think this trickiness is hinting that the HTML code could benefit from some rearrangement.
> > I am envisioning moving the code around so that the `AdopterApplication.adoption_exists?` check is moved outside of the deeper if statement like this:
> > ```
> > <% if allowed_to?(:create?, with: AdopterApplicationPolicy, <more policy context info> %>
> >   <% if current_user.adopter_foster_account.adopter_foster_profile %>
> >     Current form for apply to adopt
> >   <% elsif current_user.adopter_foster_account %>
> >     Current prompt for completing profile
> >   <% end %>
> > <% elsif AdopterApplication.adoption_exists? ... %>
> >   Existing adopter application status info in this block
> > <% end %>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I like this layout since it separates the adoption_exists? logic from the rest of the actionable logic. And as a plus, I think it should get us the behavior this issue wants. What are your thoughts?
> > ## testing
> > I am thinking it isn't necessary to system/feature test this button display. If the used policy already tests for the adopter and fosterer contexts, and we use the policy for the conditional logic, I think that may be sufficient. What are your thoughts on this @nsiwnf @kasugaijin ?
> 
> The proposed new structure seems good to me. The only catch here is
> 
> * To cater for the above solution, we have to lose some constraints in the policy. Like we have to allow create permission even if the profile is incomplete. This will affect the controller logic and the same redundant check will have to be applied there. I am thinking of this way.
> 
> ```
> <% if allowed_to?(:create?, with: AdopterApplicationPolicy, <more policy context info> %>
>     Current form for apply to adopt
> <% else> 
>     <% if AdopterApplication.adoption_exists?... %>
>        Existing adopter application status info in this block
>     <% elsif current_user.adopter_foster_account.present? && current_user.adopter_foster_account.adopter_foster_profile.empty? %>
>        Current prompt for completing profile
>     <%end%>
> <% end %>
> ```
> 
> This will separate your logic of whether to show the adoption form or not. If the answer is no, the else block will include the logic of the alternative component which we will be rendering based on some checks.
> 
> Also, this will not alter the logic of existing policy. Thoughts? @mononoken

That looks good @Harry-kp ! Thanks for catching the policy prechecks conflict.
